_BASE_: "./aadi_rpn_faster_rcnn.yaml"
MODEL:
  RESNETS:
    DEFORM_ON_PER_STAGE: [False, True, True, True] # on Res3,Res4,Res5
    DEFORM_MODULATED: False
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
  AMP:
    ENABLED: False
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
TEST:
  EVAL_PERIOD: 5000
