_BASE_: "./aadi_rpn_faster_rcnn.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  RESNETS:
    DEPTH: 101
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
TEST:
  EVAL_PERIOD: 5000
