_BASE_: "../Base-RetinaNet.yaml"
MODEL:
  META_ARCHITECTURE: "AADIRetinaNet"
  RETINANET:
    IOU_THRESHOLDS: [0.6]
    IOU_LABELS: [0, 1]
    NUM_CONVS: 3          # original implementation is 4,
    # For AADI, we do not need to design the size and scale of anchor,
    # but need to specify the value of CANDIDATE_DILATION
    CONV_KERNEL_SIZE: 3
    CANDIDATE_DILATION: [2]
    NMS_THRESH_TEST: 0.6
    # Before NMS, RetinaNet keep TOPK_CANDIDATES_TEST boxes per level,
    # we keep TOPK_CANDIDATES_TEST boxes per image.
    TOPK_CANDIDATES_TEST: 2000
    SMOOTH_L1_LOSS_BETA: 0.0
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  BASE_LR: 0.02
